# Generated by Django 5.1.5 on 2025-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='accounts.specialization'),
        ),
    ]
